### ISSUE TITLE
compatibilite Python 3

### ISSUE THREAD

**Issue by Dilomos** [Pinaute/OctoPrint_FreeMobile-Notifier#4]
Bonjour,

Avec la mise a jour Octoprint 1.4.0 python est passé en version 3, hors ce plugin ne fonctionne plus sous python 3.

Peut etre pourrez vous le rendre compatible?

Cordialement.

**Comment by Dilomos** [comment]
Après une rapide analyse du problème il suffit de remplacer la ligne 45 de __init__.py par :
filename = payload["name"]

et je pense qu'il faudrait également ajouter la ligne suivante dans setup.py :
__plugin_pythoncompat__ = ">=2.7,<4"

et bien sur incrementer le plugin_version

tester sur mon octoprint ;)

**Comment by Pinaute** [comment]
Merci de votre contribution, j'ai appliqué les changements.
