### ISSUE TITLE
Octoprint 1.4.0 - Settings and data problems

### ISSUE THREAD

**Issue by Bagu** [Pinaute/OctoPrint_FreeMobile-Notifier#6]
Bonjour,

J'ai installé ce plugin lorsque j'étais sur octoprint 1.3.12.
Lors de la migration vers octoprint 1.4.0, il a cessé de fonctionner.
J'ai donc tenté de supprimer le plugin.
Le problème, c'est que le répertoire des données est insupprimable.
Pire, si je tente de réinstaller le plugin, la page des paramètres est interactive, mais il est impossible d'enregistrer quoi que ce soit. Le bouton "enregistrer" présente un rond tournant.

En somme, il y a un soucis, mais impossible de corriger le problème.

Il s'agit d'un serveur octoprint sur une respbian.

**Comment by Pinaute** [comment]
@Bagu

>  J'ai donc tenté de supprimer le plugin.

Quel est le message d’erreur qui est affiché dans l’interface graphique ?

>  Le problème, c'est que le répertoire des données est insupprimable.

Quel est le nom du répertoire que vous voulez supprimer et quel est le message d’erreur ?

**Comment by Bagu** [comment]
> Quel est le message d’erreur qui est affiché dans l’interface graphique ?
Il n'y a pas d'erreur... Dans les logs non plus d'ailleurs, c'est ce qui est surprenant.

> Quel est le nom du répertoire que vous voulez supprimer et quel est le message d’erreur ?
Lorsque vous êtes sur octoprint, dans gestion des plugins, Cleanup, freemobilenotifier ->action "Cleanup data"
Et lorsque le plugin est supprimé, freemobilenotifier reste proposé dans la section cleanup

Un petit dessin valant mieux qu'on long discours, voici ce que j'ai, que le module soit installé ou non : 
![cleanup](https://user-images.githubusercontent.com/41675/80917604-63dc9a00-8d60-11ea-90a3-a13d31be5a5b.jpg)

Et voici ce que j'ai lorsque j'ai le plugin d'installé et que je veux aller enregistrer des paramètres : 
![savebutton](https://user-images.githubusercontent.com/41675/80917682-fbda8380-8d60-11ea-83b4-d991bed7ee2a.jpg)

Dans ce deuxième screen, peu importe ce que je fais, les petits points blanc du bouton enregistrer tournent en boucle, le bouton est cliquablen mais ne ferme pas la fenêtre.
Le seul moyen de quitter est d'utiliser la croix et si je rouvre la page, rien n'a été sauvé.

En somme, tout se passe comme si je n'avais pas les droits en écriture pour sauver les paramètres et/ou supprimer le module et ses paramètres.

**Comment by thomasnastorg** [comment]
Hi, 
@Bagu Avez vous vérifier que votre compte soit toujours en administrateur? 
comme sur l'image-ci dessous
![image](https://user-images.githubusercontent.com/24978189/80919989-406c1c00-8d6d-11ea-9e55-8250bba83ad3.png)

**Comment by Bagu** [comment]
Bonjour,

C'était bien le cas.
Bon, par contre, j'ai remarqué que d'autres plugins étaient aussi touchés.
Aucun message d'erreur dans les logs, j'ai fini par en avoir un petit peu marre (je suis dessus depuis deux jours), du coup, j'ai tout viré, et tout remis en partant de 0.
J'ai un Octoprint tout neuf, et tout refonctionne.

Je suppose donc que le soucis venait de mon installation d'octoprint qui n'a pas dû aimer la mise à jour de la version 1.3.12 à la 1.4.0

Merci du temps que vous m'avez accordé.
